swagger: '2.0'
info:
  version: 0.0.1-SNAPSHOT
  title: Recipe Master - Recipe-API.
  description: >
    
    

host: 127.0.0.1:8080

basePath: /

schemes:
  - https
  - http

consumes:
  - application/json

produces:
  - application/json

tags:
  - name: recipe-master

paths:
  /recipes:
    get:
      summary: Returns a recipe with the given name.
      description: Takes the short recipe name and returns the recipe behind it.
      operationId: retrieve-recipe
      tags:
        - recipe-master
      parameters:
        - name: recipeIdentifier
          in: query
          required: true
          description: The unique recipe identifier
          type: string
      responses:
        '200':
          description: OK.
          schema:
            type: object
            $ref: '#/definitions/Recipe'
        '404':
          description: Recipe not found.
    post:
      summary: Created a recipe.
      operationId: create-recipe
      tags:
        - recipe-master
      parameters:
        - name: recipeObject
          in: body
          required: true
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        '200':
          description: OK.
        '400':
          description: Bad Request.
    put:
      summary: Updates a recipe with new information.
      operationId: put-recipe
      tags:
        - recipe-master
      parameters:
        - name: recipeIdentifier
          in: path
          required: true
          type: string
        - name: recipeObject
          in: body
          required: true
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        '200':
          description: OK.
        '400':
          description: Bad Request.
    delete:
      summary: Deletes a recipe.
      operationId: delete-recipe
      parameters:
        - name: recipeIdentifier
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK.
        '404':
          description: Not Found.



definitions:
  Recipe:
    type: object
    description: Contains a recipe
    properties:
      identifier:
        type: string
        description: Holds the shortened unique identifier of the recipe
      title:
        type: string
      category:
        type: object
        $ref: '#/definitions/RecipeCategory'
      picture:
        type: string
      description:
        type: string
      link:
        type: string
      created-at:
        type: string
        format: date-time
  RecipeCategory:
    type: object
    properties:
      name:
        type: string
      parent:
        type: object
        $ref: '#/definitions/RecipeCategory'
