version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "recipe-master"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: