server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:recipe-master
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true