# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend-test

on:
  [ push, pull_request ]

jobs:
  test:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
#        working-directory: frontend
#      - name: Run Tests
#        run: npm test
        working-directory: frontend
      - name: Build Application
        run: npm run build
        working-directory: frontend